[package]
name = "desktop-foundation-demo"
version = "0.1.0"
description = "Desktop Foundation Demo"
edition = "2021"

[lib]
name = "desktop_foundation_demo_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
desktop-core-rs = { git = "ssh://git@github.com/k2safe/desktop-foundation.git", rev = "f61551b27c43e019ff6954726f4fadb19ce9b056", package = "desktop-core-rs", features = ["tauri"] }
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
