import {
  createDesktopClient,
  createTauriDesktopCapability,
  createTauriFileCapability,
  createTauriKeyValueStore,
  createTauriSecureStorage,
  createTauriSessionStore,
  type AppUpdateCapability,
  type AppUpdateInfo,
  type AppUpdateState,
  type AsyncKeyValueStore,
  type DesktopCapability,
  type DesktopClient,
  type FileCapability,
  type HttpTransport,
  type HttpTransportRequest,
  type KeyValueStore,
  type SessionStore
} from "@desktop-foundation/bridge";
import { invoke } from "@tauri-apps/api/core";
import { demoUser, orders, type DemoUser } from "./data";

const product = "demo-product";
const demoVersion = "0.1.0";
const apiBaseURL = "https://api.foundation-demo.local";

function isTauriRuntime() {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

function memoryStore(initialValues: Record<string, unknown> = {}): KeyValueStore {
  const values = new Map<string, unknown>(Object.entries(initialValues));
  return {
    get: <T,>(key: string) => (values.has(key) ? (values.get(key) as T) : null),
    set: (key, value) => {
      values.set(key, value);
    },
    remove: (key) => {
      values.delete(key);
    }
  };
}

function memorySecureStore(): AsyncKeyValueStore {
  const values = new Map<string, unknown>();
  return {
    async get<T>(key: string) {
      return values.has(key) ? (values.get(key) as T) : null;
    },
    async set(key, value) {
      values.set(key, value);
    },
    async remove(key) {
      values.delete(key);
    }
  };
}

function demoSessionStore(): SessionStore {
  let token: string | null = null;
  return {
    getToken: () => token,
    setToken: (nextToken) => {
      token = nextToken;
    },
    clearToken: () => {
      token = null;
    }
  };
}

function demoTransport(): HttpTransport {
  return {
    async request<T>(request: HttpTransportRequest) {
      if (request.url.endsWith("/auth/login")) {
        const payload = request.body as { account?: string; password?: string; remember?: boolean };
        if (!payload.account || !payload.password) throw new Error("Account and password are required");
        return { token: "demo-token", remember: payload.remember, user: demoUser } as T;
      }
      if (request.url.endsWith("/me")) return demoUser as T;
      if (request.url.endsWith("/orders")) return { rows: orders, total: orders.length } as T;
      return { ok: true, method: request.method, url: request.url, requestId: request.requestId } as T;
    }
  };
}

function demoDesktopCapability(pushLog: (value: string) => void): DesktopCapability {
  return {
    async openExternal(url) {
      pushLog(`openExternal ${url}`);
    },
    async copyText(text) {
      pushLog(`copyText ${text}`);
    },
    async notify(options) {
      pushLog(`notify ${options.title}`);
    },
    async getWindowState() {
      return { x: 80, y: 80, width: 1280, height: 820, maximized: false, fullscreen: false };
    },
    async setWindowState(state) {
      pushLog(`setWindowState ${JSON.stringify(state)}`);
    },
    async setWindowTitle(title) {
      pushLog(`setWindowTitle ${title}`);
    }
  };
}

function demoFileCapability(pushLog: (value: string) => void): FileCapability {
  return {
    async openFileDialog() {
      pushLog("openFileDialog");
      return { paths: ["/tmp/foundation-demo.csv"], canceled: false };
    },
    async saveFileDialog() {
      pushLog("saveFileDialog");
      return { path: "/tmp/foundation-export.json", canceled: false };
    },
    async readTextFile(path) {
      pushLog(`readTextFile ${path}`);
      return "id,merchant,amount";
    },
    async writeTextFile(path) {
      pushLog(`writeTextFile ${path}`);
      return path;
    },
    async exportJson(fileName) {
      pushLog(`exportJson ${fileName}`);
      return `/tmp/${fileName}`;
    },
    async downloadFile(url) {
      pushLog(`downloadFile ${url}`);
      return { path: "/tmp/foundation-report.csv", bytes: 2048, status: 200 };
    }
  };
}

const demoAvailableUpdate: AppUpdateInfo = {
  version: "0.1.1",
  currentVersion: demoVersion,
  channel: "stable",
  notes: "Demo release manifest generated by desktop-foundation-ci. Includes packaged .app, release .zip, and update metadata.",
  pubDate: "2026-06-02T00:00:00.000Z",
  releasePageUrl: "https://github.com/k2safe/desktop-foundation-demo/releases/tag/v0.1.1",
  downloadUrl: "https://github.com/k2safe/desktop-foundation-demo/releases/download/v0.1.1/desktop-foundation-demo-0.1.1-macos.zip",
  mandatory: false,
  metadata: {
    artifactName: "desktop-foundation-demo-0.1.1-macos.zip",
    generatedBy: "desktop-foundation-ci"
  }
};

function demoUpdateCapability(pushLog: (value: string) => void): AppUpdateCapability {
  const state: AppUpdateState = { status: "idle", currentVersion: demoVersion };

  return {
    async checkForUpdate() {
      state.status = "checking";
      pushLog("update check stable manifest");
      await new Promise((resolve) => window.setTimeout(resolve, 180));
      state.status = "available";
      state.checkedAt = Date.now();
      state.update = demoAvailableUpdate;
      return { available: true, currentVersion: demoVersion, update: demoAvailableUpdate, checkedAt: state.checkedAt };
    },
    async downloadUpdate(update = state.update ?? demoAvailableUpdate) {
      state.status = "downloading";
      pushLog(`update download ${update.version}`);
      await new Promise((resolve) => window.setTimeout(resolve, 260));
      state.status = "downloaded";
      state.downloadedPath = `/tmp/Desktop Foundation Demo-${update.version}.zip`;
      return { path: state.downloadedPath, bytes: 14_680_064, status: 200, requestId: "demo-update-download" };
    },
    async installUpdate(update = state.update ?? demoAvailableUpdate) {
      pushLog(`update install requested ${update.version}`);
      state.status = "downloaded";
    },
    async openUpdatePage(update = state.update ?? demoAvailableUpdate) {
      pushLog(`update open release ${update.releasePageUrl ?? update.downloadUrl}`);
      if (update.releasePageUrl) window.open(update.releasePageUrl, "_blank", "noopener,noreferrer");
    },
    getState: () => ({ ...state })
  };
}

export async function createDemoProductClient(pushLog: (value: string) => void): Promise<DesktopClient> {
  if (isTauriRuntime()) {
    const session = await createTauriSessionStore(invoke, product);
    return createDesktopClient({
      product,
      apiBaseURL,
      session,
      storage: createTauriKeyValueStore(invoke, product, "user", { "orders.density": "default" }),
      secureStorage: createTauriSecureStorage(invoke, product),
      transport: demoTransport(),
      desktop: createTauriDesktopCapability(invoke),
      files: createTauriFileCapability(invoke, product),
      version: demoVersion,
      updates: demoUpdateCapability(pushLog),
      security: {
        allowedRequestOrigins: ["api.foundation-demo.local"],
        allowedExternalOrigins: ["github.com", "docs.example.com"],
        allowedExternalSchemes: ["https"],
        allowedDownloadDirectories: ["/tmp"]
      }
    });
  }

  return createDesktopClient({
    product,
    apiBaseURL,
    session: demoSessionStore(),
    storage: memoryStore({ "orders.density": "default" }),
    secureStorage: memorySecureStore(),
    transport: demoTransport(),
    desktop: demoDesktopCapability(pushLog),
    files: demoFileCapability(pushLog),
    version: demoVersion,
    updates: demoUpdateCapability(pushLog),
    security: {
      allowedRequestOrigins: ["api.foundation-demo.local"],
      allowedExternalOrigins: ["github.com", "docs.example.com"],
      allowedExternalSchemes: ["https"],
      allowedDownloadDirectories: ["/tmp"]
    }
  });
}

export async function loginDemoUser(client: DesktopClient, payload: { account: string; password: string; remember?: boolean }) {
  return client.http.post<{ token: string; user: DemoUser; remember?: boolean }>("/auth/login", payload, { auth: false });
}
